name: Publish package to GitHub Packages
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
#       - uses: s4u/maven-settings-action@v1
#         with:
#           servers: '[{"id": "github", "username": "Amar97", "password": "${GITHUB_TOKEN}"}]'
#       - name: Build with Maven
#         env:
#           USERNAME: ${{github.actor}}
#           PASSWORD: ${{ secrets.GITHUB_TOKEN }}
#         run: mvn -B package --file pom.xml --settings settings.xml    
      - name: Publish package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
